---
# handlers file for stork

- name: restart stork-server
  ansible.builtin.systemd:
    name: isc-stork-server
    state: restarted
    enabled: yes
    
- name: restart stork-agent
  ansible.builtin.systemd:
    name: isc-stork-agent
    state: restarted
    enabled: yes
    
- name: "reload ansible_local"
  ansible.builtin.setup:
    filter: "ansible_local"